CREATE TABLE configuraciones_curso (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 curso_id BIGINT NOT NULL UNIQUE REFERENCES cursos(id) ON DELETE CASCADE,
 progreso_minimo INTEGER NOT NULL DEFAULT 100 CHECK(progreso_minimo BETWEEN 0 AND 100),
 asistencia_minima INTEGER NOT NULL DEFAULT 0 CHECK(asistencia_minima BETWEEN 0 AND 100),
 certificado_habilitado BOOLEAN NOT NULL DEFAULT FALSE,
 certificado_costo NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK(certificado_costo >= 0)
);
INSERT INTO configuraciones_curso(curso_id) SELECT id FROM cursos ON CONFLICT (curso_id) DO NOTHING;
CREATE TABLE materiales (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 leccion_id BIGINT NOT NULL REFERENCES lecciones(id) ON DELETE CASCADE,
 nombre VARCHAR(160) NOT NULL,
 tipo VARCHAR(20) NOT NULL,
 url VARCHAR(700) NOT NULL,
 descripcion VARCHAR(500),
 descargable BOOLEAN NOT NULL DEFAULT TRUE,
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_materiales_leccion ON materiales(leccion_id);
