CREATE TABLE inscripciones (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 estudiante_id BIGINT NOT NULL,
 curso_id BIGINT NOT NULL,
 tipo_acceso VARCHAR(15) NOT NULL CHECK(tipo_acceso IN ('GRATUITO','COMPRA')),
 estado VARCHAR(15) NOT NULL,
 fecha_inscripcion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uk_estudiante_curso UNIQUE(estudiante_id,curso_id)
);
CREATE TABLE progresos_leccion (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inscripcion_id BIGINT NOT NULL REFERENCES inscripciones(id) ON DELETE CASCADE,
 leccion_id BIGINT NOT NULL,
 completada BOOLEAN NOT NULL DEFAULT FALSE,
 fecha_completada TIMESTAMP,
 CONSTRAINT uk_inscripcion_leccion UNIQUE(inscripcion_id,leccion_id)
);
