name: kido-inscripcion-dev

services:
  postgres-inscripcion-dev:
    image: postgres:16-alpine
    container_name: kido-postgres-inscripcion-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: kido_inscripcion_db
      POSTGRES_USER: ${DB_USER:-kido}
      POSTGRES_PASSWORD: ${DB_PASS:?Define DB_PASS en .env}
    ports:
      - "15434:5432"
    volumes:
      - kido_inscripcion_dev_data:/var/lib/postgresql/data

volumes:
  kido_inscripcion_dev_data:
