package pe.edu.upeu.inscripcion.service;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.edu.upeu.inscripcion.dto.*; import pe.edu.upeu.inscripcion.entity.*; import pe.edu.upeu.inscripcion.exception.ResourceNotFoundException; import pe.edu.upeu.inscripcion.mapper.InscripcionMapper; import pe.edu.upeu.inscripcion.repository.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor
public class InscripcionService {
 private final InscripcionRepository repository; private final AsistenciaRepository asistenciaRepo; private final CertificadoRepository certificadoRepo; private final InscripcionMapper mapper; private final pe.edu.upeu.inscripcion.messaging.AcademicoEventosProducer eventos;
 @Transactional(readOnly=true) public List<InscripcionResponse> listar(){return repository.findAllConProgresos().stream().map(mapper::toResponse).toList();}
 @Transactional(readOnly=true) public List<InscripcionResponse> porEstudiante(Long id){return repository.findByEstudianteIdOrderByIdDesc(id).stream().map(mapper::toResponse).toList();}
 @Transactional(readOnly=true) public List<InscripcionResponse> porCurso(Long id){return repository.findByCursoIdOrderByIdDesc(id).stream().map(mapper::toResponse).toList();}
 @Transactional(readOnly=true) public InscripcionResponse obtener(Long id){return mapper.toResponse(buscar(id));}
 private void reglas(Inscripcion i,Integer progreso,Integer asistencia,Boolean cert,BigDecimal costo){i.setProgresoMinimo(progreso==null?100:Math.max(0,Math.min(100,progreso)));i.setAsistenciaMinima(asistencia==null?0:Math.max(0,Math.min(100,asistencia)));i.setCertificadoHabilitado(Boolean.TRUE.equals(cert));i.setCertificadoCosto(costo==null?BigDecimal.ZERO:costo.max(BigDecimal.ZERO));}
 private void progresos(Inscripcion i,List<Long> ids){if(ids!=null) ids.stream().filter(Objects::nonNull).distinct().forEach(id->{ProgresoLeccion p=new ProgresoLeccion();p.setLeccionId(id);p.setInscripcion(i);i.getProgresos().add(p);});}
 @Transactional public InscripcionResponse crear(InscripcionRequest r){if(repository.existsByEstudianteIdAndCursoId(r.estudianteId(),r.cursoId()))throw new IllegalArgumentException("El estudiante ya está inscrito en este curso");Inscripcion i=new Inscripcion();i.setEstudianteId(r.estudianteId());i.setCursoId(r.cursoId());try{i.setTipoAcceso(Inscripcion.TipoAcceso.valueOf(r.tipoAcceso().toUpperCase()));}catch(Exception e){throw new IllegalArgumentException("tipoAcceso debe ser GRATUITO o COMPRA");}if(i.getTipoAcceso()==Inscripcion.TipoAcceso.COMPRA)throw new IllegalArgumentException("Las inscripciones por COMPRA solo se crean tras un pago aprobado");i.setEstado(Inscripcion.EstadoInscripcion.ACTIVA);i.setFechaInscripcion(LocalDateTime.now());reglas(i,r.progresoMinimo(),r.asistenciaMinima(),r.certificadoHabilitado(),r.certificadoCosto());progresos(i,r.leccionIds());return mapper.toResponse(repository.save(i));}
 @Transactional public InscripcionResponse crearPorCompra(CompraInscripcionRequest r){Optional<Inscripcion> ex=repository.findByEstudianteIdAndCursoIdConProgresos(r.estudianteId(),r.cursoId());if(ex.isPresent()){Inscripcion i=ex.get();if(i.getTipoAcceso()!=Inscripcion.TipoAcceso.COMPRA)throw new IllegalStateException("Ya existe una inscripción gratuita");if(i.getEstado()==Inscripcion.EstadoInscripcion.REVOCADA||i.getEstado()==Inscripcion.EstadoInscripcion.CANCELADA)i.setEstado(Inscripcion.EstadoInscripcion.ACTIVA);reglas(i,r.progresoMinimo(),r.asistenciaMinima(),r.certificadoHabilitado(),r.certificadoCosto());Set<Long> existentes=new HashSet<>(i.getProgresos().stream().map(ProgresoLeccion::getLeccionId).toList());if(r.leccionIds()!=null)r.leccionIds().stream().filter(x->!existentes.contains(x)).forEach(x->{ProgresoLeccion p=new ProgresoLeccion();p.setLeccionId(x);p.setInscripcion(i);i.getProgresos().add(p);});return mapper.toResponse(repository.save(i));}Inscripcion i=new Inscripcion();i.setEstudianteId(r.estudianteId());i.setCursoId(r.cursoId());i.setTipoAcceso(Inscripcion.TipoAcceso.COMPRA);i.setEstado(Inscripcion.EstadoInscripcion.ACTIVA);i.setFechaInscripcion(LocalDateTime.now());reglas(i,r.progresoMinimo(),r.asistenciaMinima(),r.certificadoHabilitado(),r.certificadoCosto());progresos(i,r.leccionIds());return mapper.toResponse(repository.save(i));}
 @Transactional(readOnly=true) public InscripcionResponse buscarPorEstudianteCurso(Long e,Long c){return mapper.toResponse(repository.findByEstudianteIdAndCursoIdConProgresos(e,c).orElseThrow(()->new ResourceNotFoundException("Inscripción no encontrada")));}
 @Transactional public InscripcionResponse revocarPorReembolso(Long e,Long c){Inscripcion i=repository.findByEstudianteIdAndCursoIdConProgresos(e,c).orElseThrow(()->new ResourceNotFoundException("Inscripción no encontrada"));if(i.getTipoAcceso()!=Inscripcion.TipoAcceso.COMPRA)throw new IllegalArgumentException("Solo una inscripción por compra puede revocarse");i.setEstado(Inscripcion.EstadoInscripcion.REVOCADA);certificadoRepo.findByInscripcionId(i.getId()).ifPresent(x->{x.setEstado(Certificado.EstadoCertificado.ANULADO);certificadoRepo.save(x);});return mapper.toResponse(repository.save(i));}
 @Transactional public InscripcionResponse cambiarEstado(Long id,EstadoRequest r){Inscripcion i=buscar(id);try{i.setEstado(Inscripcion.EstadoInscripcion.valueOf(r.estado().toUpperCase()));}catch(Exception e){throw new IllegalArgumentException("Estado no válido");}return mapper.toResponse(repository.save(i));}
 @Transactional public InscripcionResponse completarLeccion(Long id,Long leccionId){Inscripcion i=buscar(id);if(i.getEstado()!=Inscripcion.EstadoInscripcion.ACTIVA)throw new IllegalArgumentException("La inscripción no está activa");ProgresoLeccion p=i.getProgresos().stream().filter(x->x.getLeccionId().equals(leccionId)).findFirst().orElseThrow(()->new ResourceNotFoundException("La lección no pertenece a esta inscripción"));p.setCompletada(true);p.setFechaCompletada(LocalDateTime.now());boolean completo=evaluarYCerrar(i);Inscripcion guardada=repository.save(i);if(completo) publicar(i,"curso.completado");return mapper.toResponse(guardada);}
 @Transactional public AsistenciaResponse registrarAsistencia(Long id,AsistenciaRequest r){Inscripcion i=buscar(id);Asistencia a=asistenciaRepo.findByInscripcionIdAndFechaClase(id,r.fechaClase()).orElseGet(Asistencia::new);a.setInscripcion(i);a.setFechaClase(r.fechaClase());try{a.setEstado(Asistencia.EstadoAsistencia.valueOf(r.estado().toUpperCase()));}catch(Exception e){throw new IllegalArgumentException("Estado de asistencia no válido");}a.setObservacion(r.observacion());a.setFechaRegistro(LocalDateTime.now());a=asistenciaRepo.save(a);boolean completo=evaluarYCerrar(i);repository.save(i);if(completo) publicar(i,"curso.completado");return map(a);}
 @Transactional(readOnly=true) public List<AsistenciaResponse> asistencias(Long id){buscar(id);return asistenciaRepo.findByInscripcionIdOrderByFechaClaseDesc(id).stream().map(this::map).toList();}
 @Transactional(readOnly=true) public EstadoAcademicoResponse estadoAcademico(Long id){Inscripcion i=buscar(id);return estado(i);}
 private int progreso(Inscripcion i){if(i.getProgresos().isEmpty())return 0;return (int)Math.round(i.getProgresos().stream().filter(ProgresoLeccion::isCompletada).count()*100.0/i.getProgresos().size());}
 private int asistencia(Long id){long total=asistenciaRepo.countByInscripcionId(id);if(total==0)return 0;long presentes=asistenciaRepo.countByInscripcionIdAndEstadoIn(id,List.of(Asistencia.EstadoAsistencia.PRESENTE,Asistencia.EstadoAsistencia.TARDE,Asistencia.EstadoAsistencia.JUSTIFICADA));return (int)Math.round(presentes*100.0/total);}
 private EstadoAcademicoResponse estado(Inscripcion i){int p=progreso(i),a=asistencia(i.getId());boolean cp=p>=i.getProgresoMinimo(),ca=a>=i.getAsistenciaMinima();return new EstadoAcademicoResponse(i.getId(),p,a,i.getProgresoMinimo(),i.getAsistenciaMinima(),cp,ca,i.isCertificadoHabilitado()&&cp&&ca,i.getEstado().name());}
 private boolean evaluarYCerrar(Inscripcion i){EstadoAcademicoResponse e=estado(i);boolean cumple=e.cumpleProgreso()&&e.cumpleAsistencia();boolean nuevo=cumple&&i.getEstado()==Inscripcion.EstadoInscripcion.ACTIVA;if(nuevo)i.setEstado(Inscripcion.EstadoInscripcion.COMPLETADA);else if(!cumple&&i.getEstado()==Inscripcion.EstadoInscripcion.COMPLETADA)i.setEstado(Inscripcion.EstadoInscripcion.ACTIVA);return nuevo;}
 private void publicar(Inscripcion i,String tipo){eventos.publicarTrasCommit(pe.edu.upeu.inscripcion.event.AcademicoEvento.builder().tipoEvento(tipo).estudianteId(i.getEstudianteId()).cursoId(i.getCursoId()).estado(i.getEstado().name()).origen("kido-inscripcion-ms").timestamp(java.time.Instant.now().toEpochMilli()).build());}
 @Transactional public CertificadoResponse solicitarCertificado(Long id){Inscripcion i=buscar(id);EstadoAcademicoResponse e=estado(i);if(!i.isCertificadoHabilitado())throw new IllegalStateException("El curso no habilita certificado");if(!e.elegibleCertificado())throw new IllegalStateException("Aún no cumple progreso y asistencia mínimos");Certificado c=certificadoRepo.findByInscripcionId(id).orElseGet(Certificado::new);c.setInscripcionId(id);if(c.getCodigo()==null)c.setCodigo("KIDO-CERT-"+String.format("%08d",id)+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());c.setCosto(i.getCertificadoCosto());if(i.getCertificadoCosto().compareTo(BigDecimal.ZERO)==0){c.setPagoConfirmado(true);c.setEstado(Certificado.EstadoCertificado.DISPONIBLE);c.setFechaEmision(LocalDateTime.now());}else{c.setEstado(Certificado.EstadoCertificado.PENDIENTE_PAGO);}Certificado guardado=certificadoRepo.save(c);if(guardado.getEstado()==Certificado.EstadoCertificado.DISPONIBLE)publicar(i,"certificado.disponible");return map(guardado);}
 @Transactional public CertificadoResponse confirmarPagoCertificado(Long id){Certificado c=certificadoRepo.findByInscripcionId(id).orElseThrow(()->new ResourceNotFoundException("Certificado no solicitado"));c.setPagoConfirmado(true);c.setEstado(Certificado.EstadoCertificado.DISPONIBLE);c.setFechaEmision(LocalDateTime.now());Certificado guardado=certificadoRepo.save(c);Inscripcion i=buscar(id);publicar(i,"certificado.disponible");return map(guardado);}
 @Transactional(readOnly=true) public CertificadoResponse certificado(Long id){return map(certificadoRepo.findByInscripcionId(id).orElseThrow(()->new ResourceNotFoundException("Certificado no encontrado")));}
 @Transactional public void eliminar(Long id){repository.delete(buscar(id));}
 private Inscripcion buscar(Long id){return repository.findByIdConProgresos(id).orElseThrow(()->new ResourceNotFoundException("Inscripción no encontrada: "+id));}
 private AsistenciaResponse map(Asistencia a){return new AsistenciaResponse(a.getId(),a.getInscripcion().getId(),a.getFechaClase(),a.getEstado().name(),a.getObservacion(),a.getFechaRegistro());}
 private CertificadoResponse map(Certificado c){return new CertificadoResponse(c.getId(),c.getInscripcionId(),c.getCodigo(),c.getEstado().name(),c.getCosto(),c.isPagoConfirmado(),c.getFechaEmision());}
}
