CREATE TABLE ordenes_compra (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 estudiante_id BIGINT NOT NULL, curso_id BIGINT NOT NULL, docente_id BIGINT NOT NULL,
 curso_titulo VARCHAR(180) NOT NULL, monto_total NUMERIC(10,2) NOT NULL CHECK(monto_total>0),
 porcentaje_comision NUMERIC(5,2) NOT NULL, comision_kido NUMERIC(10,2) NOT NULL,
 monto_docente NUMERIC(10,2) NOT NULL, estado VARCHAR(24) NOT NULL,
 mp_preference_id VARCHAR(120), mp_payment_id VARCHAR(120) UNIQUE,
 inscripcion_sincronizada BOOLEAN NOT NULL DEFAULT FALSE,
 fecha_creacion TIMESTAMP NOT NULL, fecha_aprobacion TIMESTAMP
);
CREATE TABLE movimientos_saldo (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, docente_id BIGINT NOT NULL,
 orden_id BIGINT, retiro_id BIGINT, tipo VARCHAR(20) NOT NULL, estado VARCHAR(20) NOT NULL,
 monto NUMERIC(10,2) NOT NULL, fecha_disponible TIMESTAMP, fecha_creacion TIMESTAMP NOT NULL,
 descripcion VARCHAR(300)
);
CREATE UNIQUE INDEX uk_mov_venta_orden ON movimientos_saldo(orden_id,tipo) WHERE tipo='VENTA';
CREATE TABLE retiros (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, docente_id BIGINT NOT NULL,
 monto NUMERIC(10,2) NOT NULL CHECK(monto>=50), medio VARCHAR(20) NOT NULL, destino VARCHAR(160) NOT NULL,
 estado VARCHAR(20) NOT NULL, codigo_operacion VARCHAR(120), motivo_rechazo VARCHAR(300),
 movimiento_id BIGINT, fecha_solicitud TIMESTAMP NOT NULL, fecha_proceso TIMESTAMP
);
CREATE TABLE reembolsos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, orden_id BIGINT NOT NULL UNIQUE,
 estudiante_id BIGINT NOT NULL, curso_id BIGINT NOT NULL, monto NUMERIC(10,2) NOT NULL,
 motivo VARCHAR(500) NOT NULL, porcentaje_progreso INTEGER NOT NULL, estado VARCHAR(20) NOT NULL,
 fecha_solicitud TIMESTAMP NOT NULL, fecha_proceso TIMESTAMP, motivo_rechazo VARCHAR(300)
);
