CREATE TABLE ordenes_certificado (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inscripcion_id BIGINT NOT NULL,
 estudiante_id BIGINT NOT NULL,
 curso_id BIGINT NOT NULL,
 docente_id BIGINT NOT NULL,
 monto_total NUMERIC(10,2) NOT NULL CHECK(monto_total>0),
 comision_kido NUMERIC(10,2) NOT NULL,
 monto_docente NUMERIC(10,2) NOT NULL,
 estado VARCHAR(24) NOT NULL,
 mp_preference_id VARCHAR(120),
 mp_payment_id VARCHAR(120) UNIQUE,
 fecha_creacion TIMESTAMP NOT NULL,
 fecha_aprobacion TIMESTAMP
);
CREATE INDEX idx_orden_cert_inscripcion ON ordenes_certificado(inscripcion_id);
