package pe.edu.upeu.pago.service;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.edu.upeu.pago.client.*; import pe.edu.upeu.pago.dto.*; import pe.edu.upeu.pago.entity.*; import pe.edu.upeu.pago.exception.ResourceNotFoundException; import pe.edu.upeu.pago.repository.*; import java.math.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor
public class CertificadoPagoService {
 private final OrdenCertificadoRepository repo; private final MovimientoSaldoRepository movRepo; private final InscripcionClient inscripcionClient; private final CursoClient cursoClient; private final MercadoPagoClient mp;
 @Value("${kido.pagos.comision:0.10}") private BigDecimal comision; @Value("${kido.pagos.dias-retencion:7}") private long diasRetencion; @Value("${kido.pagos.permitir-simulacion:false}") private boolean simulacion;
 @Transactional public OrdenCertificadoResponse crear(CrearOrdenCertificadoRequest r){InscripcionDto ins=inscripcionClient.buscar(r.estudianteId(),r.cursoId());if(ins==null||!r.inscripcionId().equals(ins.id()))throw new IllegalArgumentException("La inscripción no corresponde al estudiante y curso indicados");CertificadoInscripcionDto cert=inscripcionClient.certificado(r.inscripcionId());if(cert==null)throw new ResourceNotFoundException("Certificado no encontrado");if(!"PENDIENTE_PAGO".equals(cert.estado()))throw new IllegalStateException("El certificado no está pendiente de pago");if(cert.costo()==null||cert.costo().compareTo(BigDecimal.ZERO)<=0)throw new IllegalStateException("El certificado no requiere pago");var existente=repo.findFirstByInscripcionIdAndEstadoInOrderByIdDesc(r.inscripcionId(),List.of(OrdenCertificado.EstadoOrden.PENDIENTE,OrdenCertificado.EstadoOrden.PAGO_INICIADO,OrdenCertificado.EstadoOrden.APROBADA));if(existente.isPresent())return map(existente.get());CursoCompraDto c=cursoClient.obtener(r.cursoId());OrdenCertificado o=new OrdenCertificado();o.setInscripcionId(r.inscripcionId());o.setEstudianteId(r.estudianteId());o.setCursoId(r.cursoId());o.setDocenteId(c.docenteId());o.setMontoTotal(cert.costo().setScale(2,RoundingMode.HALF_UP));o.setComisionKido(o.getMontoTotal().multiply(comision).setScale(2,RoundingMode.HALF_UP));o.setMontoDocente(o.getMontoTotal().subtract(o.getComisionKido()));o.setEstado(OrdenCertificado.EstadoOrden.PENDIENTE);o.setFechaCreacion(LocalDateTime.now());return map(repo.save(o));}
 @Transactional public PreferenciaResponse iniciar(Long id){OrdenCertificado o=buscar(id);if(o.getEstado()==OrdenCertificado.EstadoOrden.APROBADA)throw new IllegalStateException("La orden ya fue pagada");PreferenciaResponse p=mp.crearPreferencia("Certificado KIDO - curso "+o.getCursoId(),o.getMontoTotal(),"CERT-"+o.getId());o.setMercadoPagoPreferenceId(p.preferenceId());o.setEstado(OrdenCertificado.EstadoOrden.PAGO_INICIADO);repo.save(o);return p;}
 @Transactional public OrdenCertificadoResponse confirmar(Long id,String paymentId){OrdenCertificado o=buscar(id);if(o.getEstado()==OrdenCertificado.EstadoOrden.APROBADA)return map(o);var p=mp.obtenerPago(paymentId);if(!"approved".equalsIgnoreCase(p.status()))throw new IllegalStateException("Mercado Pago aún no reporta approved");if(!("CERT-"+id).equals(p.externalReference()))throw new IllegalArgumentException("El pago no corresponde a esta orden de certificado");if(p.amount()!=null&&new BigDecimal(p.amount()).compareTo(o.getMontoTotal())!=0)throw new IllegalArgumentException("El monto aprobado no coincide");return aprobar(o,p.id());}
 @Transactional public OrdenCertificadoResponse simular(Long id){if(!simulacion)throw new IllegalStateException("La simulación solo está habilitada en DEV");return aprobar(buscar(id),"SIM-CERT-"+UUID.randomUUID());}
 @Transactional public OrdenCertificadoResponse procesarWebhook(String paymentId,String referencia){if(referencia==null||!referencia.startsWith("CERT-"))throw new IllegalArgumentException("Referencia de certificado inválida");return confirmar(Long.valueOf(referencia.substring(5)),paymentId);}
 private OrdenCertificadoResponse aprobar(OrdenCertificado o,String paymentId){repo.findByMercadoPagoPaymentId(paymentId).filter(x->!x.getId().equals(o.getId())).ifPresent(x->{throw new IllegalStateException("paymentId ya utilizado");});o.setEstado(OrdenCertificado.EstadoOrden.APROBADA);o.setMercadoPagoPaymentId(paymentId);o.setFechaAprobacion(LocalDateTime.now());repo.save(o);inscripcionClient.confirmarPagoCertificado(o.getInscripcionId());MovimientoSaldo m=new MovimientoSaldo();m.setDocenteId(o.getDocenteId());m.setOrdenId(null);m.setTipo(MovimientoSaldo.TipoMovimiento.CERTIFICADO);m.setEstado(MovimientoSaldo.EstadoMovimiento.PENDIENTE);m.setMonto(o.getMontoDocente());m.setFechaDisponible(o.getFechaAprobacion().plusDays(diasRetencion));m.setFechaCreacion(LocalDateTime.now());m.setDescripcion("90% de certificado del curso "+o.getCursoId()+" (orden-cert "+o.getId()+")");movRepo.save(m);return map(o);}
 @Transactional(readOnly=true) public List<OrdenCertificadoResponse> estudiante(Long id){return repo.findByEstudianteIdOrderByIdDesc(id).stream().map(this::map).toList();}
 private OrdenCertificado buscar(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Orden de certificado no encontrada: "+id));}
 private OrdenCertificadoResponse map(OrdenCertificado o){return new OrdenCertificadoResponse(o.getId(),o.getInscripcionId(),o.getEstudianteId(),o.getCursoId(),o.getDocenteId(),o.getMontoTotal(),o.getComisionKido(),o.getMontoDocente(),o.getEstado().name(),o.getMercadoPagoPreferenceId(),o.getMercadoPagoPaymentId(),o.getFechaCreacion(),o.getFechaAprobacion());}
}
