package pe.edu.upeu.pago.service;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.edu.upeu.pago.dto.*; import pe.edu.upeu.pago.entity.*; import pe.edu.upeu.pago.client.NotificacionClient; import pe.edu.upeu.pago.exception.ResourceNotFoundException; import pe.edu.upeu.pago.repository.*; import java.math.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class RetiroService { private final RetiroRepository repo; private final MovimientoSaldoRepository movRepo; private final PagoService pago; private final NotificacionClient notificacion; @Value("${kido.pagos.retiro-minimo:50.00}") private BigDecimal minimo;
 @Transactional public RetiroResponse solicitar(RetiroRequest r){if(r.monto().compareTo(minimo)<0)throw new IllegalArgumentException("El retiro mínimo es S/ "+minimo); if(pago.saldo(r.docenteId()).disponible().compareTo(r.monto())<0)throw new IllegalArgumentException("Saldo disponible insuficiente"); Retiro x=new Retiro();x.setDocenteId(r.docenteId());x.setMonto(r.monto().setScale(2,RoundingMode.HALF_UP)); try{x.setMedio(Retiro.MedioRetiro.valueOf(r.medio().toUpperCase()));}catch(Exception e){throw new IllegalArgumentException("Medio debe ser CUENTA_BANCARIA, YAPE o PLIN");} x.setDestino(r.destino());x.setEstado(Retiro.EstadoRetiro.PENDING);x.setFechaSolicitud(LocalDateTime.now());x=repo.save(x); MovimientoSaldo m=new MovimientoSaldo();m.setDocenteId(x.getDocenteId());m.setRetiroId(x.getId());m.setTipo(MovimientoSaldo.TipoMovimiento.RETIRO);m.setEstado(MovimientoSaldo.EstadoMovimiento.RESERVADO);m.setMonto(x.getMonto().negate());m.setFechaCreacion(LocalDateTime.now());m.setDescripcion("Reserva de retiro #"+x.getId());m=movRepo.save(m);x.setMovimientoId(m.getId());x=repo.save(x);notificacion.enviar(x.getDocenteId(),"RETIRO_SOLICITADO","Retiro solicitado","Tu solicitud de retiro por S/ "+x.getMonto()+" quedó PENDING.");return map(x);}
 @Transactional public RetiroResponse aprobar(Long id){Retiro x=get(id);if(x.getEstado()!=Retiro.EstadoRetiro.PENDING)throw new IllegalStateException("Solo un retiro PENDING puede aprobarse");x.setEstado(Retiro.EstadoRetiro.APPROVED);x.setFechaProceso(LocalDateTime.now());x=repo.save(x);notificacion.enviar(x.getDocenteId(),"RETIRO_APROBADO","Retiro aprobado","Tu retiro por S/ "+x.getMonto()+" fue aprobado.");return map(x);}
 @Transactional public RetiroResponse pagar(Long id,String codigo){Retiro x=get(id);if(x.getEstado()!=Retiro.EstadoRetiro.APPROVED)throw new IllegalStateException("El retiro debe estar APPROVED");x.setEstado(Retiro.EstadoRetiro.PAID);x.setCodigoOperacion(codigo);x.setFechaProceso(LocalDateTime.now());MovimientoSaldo m=movRepo.findById(x.getMovimientoId()).orElseThrow();m.setEstado(MovimientoSaldo.EstadoMovimiento.PAGADO);movRepo.save(m);x=repo.save(x);notificacion.enviar(x.getDocenteId(),"RETIRO_PAGADO","Retiro pagado","Se registró el pago de tu retiro. Operación: "+codigo);return map(x);}
 @Transactional public RetiroResponse rechazar(Long id,String motivo){Retiro x=get(id);if(x.getEstado()==Retiro.EstadoRetiro.PAID)throw new IllegalStateException("Un retiro pagado no puede rechazarse");x.setEstado(Retiro.EstadoRetiro.REJECTED);x.setMotivoRechazo(motivo);x.setFechaProceso(LocalDateTime.now());if(x.getMovimientoId()!=null)movRepo.findById(x.getMovimientoId()).ifPresent(m->{m.setEstado(MovimientoSaldo.EstadoMovimiento.REVERTIDO);movRepo.save(m);});x=repo.save(x);notificacion.enviar(x.getDocenteId(),"RETIRO_RECHAZADO","Retiro rechazado","Tu retiro fue rechazado: "+motivo);return map(x);}
 @Transactional(readOnly=true) public List<RetiroResponse> listar(){return repo.findAll().stream().map(this::map).toList();} @Transactional(readOnly=true) public List<RetiroResponse> porDocente(Long id){return repo.findByDocenteIdOrderByIdDesc(id).stream().map(this::map).toList();}
 private Retiro get(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Retiro no encontrado: "+id));} private RetiroResponse map(Retiro x){return new RetiroResponse(x.getId(),x.getDocenteId(),x.getMonto(),x.getMedio().name(),x.getDestino(),x.getEstado().name(),x.getCodigoOperacion(),x.getMotivoRechazo(),x.getFechaSolicitud(),x.getFechaProceso());}}
