package pe.edu.upeu.curso.controller;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import pe.edu.upeu.curso.dto.*; import pe.edu.upeu.curso.service.*;
@RestController @RequestMapping("/api/v1") @RequiredArgsConstructor
public class ContenidoCursoController { private final ContenidoCursoService service; private final MaterialStorageService storage;
 @GetMapping("/cursos/{cursoId}/contenido") public ContenidoCursoResponse contenido(@PathVariable Long cursoId){return service.contenido(cursoId);} 
 @PostMapping("/cursos/{cursoId}/modulos") public ResponseEntity<ModuloDetalleResponse> crearModulo(@PathVariable Long cursoId,@Valid @RequestBody ModuloRequest r){return ResponseEntity.status(201).body(service.crearModulo(cursoId,r));}
 @PutMapping("/modulos/{id}") public ModuloDetalleResponse actualizarModulo(@PathVariable Long id,@Valid @RequestBody ModuloRequest r){return service.actualizarModulo(id,r);} @DeleteMapping("/modulos/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void eliminarModulo(@PathVariable Long id){service.eliminarModulo(id);}
 @PostMapping("/modulos/{moduloId}/lecciones") public ResponseEntity<LeccionDetalleResponse> crearLeccion(@PathVariable Long moduloId,@Valid @RequestBody LeccionRequest r){return ResponseEntity.status(201).body(service.crearLeccion(moduloId,r));}
 @PutMapping("/lecciones/{id}") public LeccionDetalleResponse actualizarLeccion(@PathVariable Long id,@Valid @RequestBody LeccionRequest r){return service.actualizarLeccion(id,r);} @DeleteMapping("/lecciones/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void eliminarLeccion(@PathVariable Long id){service.eliminarLeccion(id);}
 @PostMapping("/lecciones/{leccionId}/materiales") public ResponseEntity<MaterialResponse> crearMaterial(@PathVariable Long leccionId,@Valid @RequestBody MaterialRequest r){return ResponseEntity.status(201).body(service.crearMaterial(leccionId,r));}
 @PostMapping(value="/lecciones/{leccionId}/materiales/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<MaterialResponse> subir(@PathVariable Long leccionId,@RequestPart("archivo") MultipartFile archivo,@RequestParam(required=false) String nombre,@RequestParam(required=false) String descripcion,@RequestParam(defaultValue="true") boolean descargable){return ResponseEntity.status(201).body(storage.guardar(leccionId,archivo,nombre,descripcion,descargable));}
 @GetMapping("/materiales/archivos/{nombre:.+}") public ResponseEntity<Resource> archivo(@PathVariable String nombre){Resource r=storage.cargar(nombre);return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"inline; filename=\""+r.getFilename()+"\"").contentType(MediaType.APPLICATION_OCTET_STREAM).body(r);}
 @PutMapping("/materiales/{id}") public MaterialResponse actualizarMaterial(@PathVariable Long id,@Valid @RequestBody MaterialRequest r){return service.actualizarMaterial(id,r);} @DeleteMapping("/materiales/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void eliminarMaterial(@PathVariable Long id){service.eliminarMaterial(id);}
 @GetMapping("/cursos/{cursoId}/configuracion") public ConfiguracionCursoResponse config(@PathVariable Long cursoId){return service.obtenerConfig(cursoId);} @PutMapping("/cursos/{cursoId}/configuracion") public ConfiguracionCursoResponse config(@PathVariable Long cursoId,@Valid @RequestBody ConfiguracionCursoRequest r){return service.configurar(cursoId,r);}
}
